<a href="https://colab.research.google.com/github/Rahul-Tanawade/neural-_networks_pytorch/blob/main/PyTorch%20Dataset_and_DataLoader%20concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

import io
import numpy as np
dataset = np.loadtxt(io.BytesIO(uploaded['wine.csv']),delimiter=",",skiprows=1,dtype=np.float32)

Saving Womens Clothing E-Commerce Reviews.csv to Womens Clothing E-Commerce Reviews.csv


KeyError: ignored

In [ ]:
import numpy as np
import torch
import torchvision
import math
import io
from torch.utils.data import Dataset, DataLoader

In [ ]:
#Data loading in PyTorch can be separated in 2 parts:
#Data must be wrapped on a Dataset parent class where the methods __getitem__ and __len__ must be overrided. 


#the __len__ function which returns the size of the dataset, and
#the __getitem__ function which returns a sample from the dataset given an index.

#__len__ so that len(dataset) returns the size of the dataset.
#__getitem__ to support the indexing such that dataset[i] can be used to get ith sample


class WineDataset(Dataset):
  def __init__(self):
    from google.colab import files
    uploaded=files.upload()
    xy = np.loadtxt(io.BytesIO(uploaded['wine.csv']),delimiter=",",skiprows=1,dtype=np.float32)
    self.x=torch.from_numpy(xy[:,1:])
    self.y=torch.from_numpy(xy[:,[0]])
    self.n_samples=xy.shape[0]


  def __getitem__(self,index):
    return(self.x[index],self.y[index])


  def __len__(self):  
    return self.n_samples

dataset1=WineDataset()     # dataset1 object is used get index for every 178 observations of loaded file , done through __getitem__
                           # dataset1 is used to get length of file loaded , done through __len__ 

print(dataset1.__dict__.keys())                           #dict_keys(['x', 'y', 'n_samples'])

Saving wine.csv to wine (1).csv
dict_keys(['x', 'y', 'n_samples'])


In [ ]:

first_data=dataset1[0] #__getitem__ is called and [0] index is pointed
print(type(first_data))
print(len(first_data))
print(first_data)

<class 'tuple'>
2
(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))


In [ ]:
dataloader=DataLoader(dataset=dataset1,batch_size=4,shuffle=True,num_workers=2)
print(dataloader.__dict__.keys())

#DataLoader class is used to create batch of dataset stored in dataset1 above. batchsize metioned is 4

dict_keys(['dataset', 'num_workers', 'prefetch_factor', 'pin_memory', 'timeout', 'worker_init_fn', '_DataLoader__multiprocessing_context', '_dataset_kind', 'batch_size', 'drop_last', 'sampler', 'batch_sampler', 'generator', 'collate_fn', 'persistent_workers', '_DataLoader__initialized', '_IterableDataset_len_called', '_iterator'])


In [ ]:
#to see first batch
dataiter=iter(dataloader)

data=dataiter.next()
features,label=data
print("\n\nfeatures : {}".format(features))
print("\n\nlabel : {}".format(label))
print("\n\n len(features : {}".format(len(features)))



features : tensor([[1.3560e+01, 1.7300e+00, 2.4600e+00, 2.0500e+01, 1.1600e+02, 2.9600e+00,
         2.7800e+00, 2.0000e-01, 2.4500e+00, 6.2500e+00, 9.8000e-01, 3.0300e+00,
         1.1200e+03],
        [1.3050e+01, 1.7700e+00, 2.1000e+00, 1.7000e+01, 1.0700e+02, 3.0000e+00,
         3.0000e+00, 2.8000e-01, 2.0300e+00, 5.0400e+00, 8.8000e-01, 3.3500e+00,
         8.8500e+02],
        [1.2370e+01, 1.1700e+00, 1.9200e+00, 1.9600e+01, 7.8000e+01, 2.1100e+00,
         2.0000e+00, 2.7000e-01, 1.0400e+00, 4.6800e+00, 1.1200e+00, 3.4800e+00,
         5.1000e+02],
        [1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]])


label : tensor([[1.],
        [1.],
        [2.],
        [1.]])


 len(features : 4


In [ ]:
print("no of samples in dataset ",len(dataset1))

no_of_batch=math.ceil(len(dataset1)/4)
data_iter=iter(dataloader)

for batch_no in  range(1,no_of_batch+1):
  features,labels=data_iter.next()
  if batch_no % 4 == 0 :#printing every multiple of 4 batch
    print("\n\nbatch no : {}".format(batch_no))
    print("\n\nfeature set : \n {}".format(features))
    print("\n\n labels set : \n {}".format(labels))


no of samples in dataset  178


batch no : 4


feature set : 
 tensor([[1.2080e+01, 1.3900e+00, 2.5000e+00, 2.2500e+01, 8.4000e+01, 2.5600e+00,
         2.2900e+00, 4.3000e-01, 1.0400e+00, 2.9000e+00, 9.3000e-01, 3.1900e+00,
         3.8500e+02],
        [1.4220e+01, 1.7000e+00, 2.3000e+00, 1.6300e+01, 1.1800e+02, 3.2000e+00,
         3.0000e+00, 2.6000e-01, 2.0300e+00, 6.3800e+00, 9.4000e-01, 3.3100e+00,
         9.7000e+02],
        [1.2510e+01, 1.7300e+00, 1.9800e+00, 2.0500e+01, 8.5000e+01, 2.2000e+00,
         1.9200e+00, 3.2000e-01, 1.4800e+00, 2.9400e+00, 1.0400e+00, 3.5700e+00,
         6.7200e+02],
        [1.2290e+01, 3.1700e+00, 2.2100e+00, 1.8000e+01, 8.8000e+01, 2.8500e+00,
         2.9900e+00, 4.5000e-01, 2.8100e+00, 2.3000e+00, 1.4200e+00, 2.8300e+00,
         4.0600e+02]])


 labels set : 
 tensor([[2.],
        [1.],
        [2.],
        [2.]])


batch no : 8


feature set : 
 tensor([[1.4100e+01, 2.1600e+00, 2.3000e+00, 1.8000e+01, 1.0500e+02, 2.9500e+00,
         3.

In [ ]:
#to upload on github

from google.colab import files
uploaded=files.upload()

import io
import numpy as np
dataset = np.loadtxt(io.BytesIO(uploaded['wine.csv']),delimiter=",",skiprows=1,dtype=np.float32)

Saving wine.csv to wine.csv


In [57]:
#Data loading in PyTorch can be separated in 2 parts:
#Data must be wrapped on a Dataset parent class where the methods __getitem__ and __len__ must be overrided. 


#the __len__ function which returns the size of the dataset, and
#the __getitem__ function which returns a sample from the dataset given an index.

#__len__ so that len(dataset) returns the size of the dataset.
#__getitem__ to support the indexing such that dataset[i] can be used to get ith sample



import torch
import torchvision
import torch.nn as nn
import numpy as np
import math
from torch.utils.data import Dataset,DataLoader 
from google.colab import files

class WineDataset(Dataset):
  def __init__(self):
    #data loading
    uploaded=files.upload()
    xy = np.loadtxt(io.BytesIO(uploaded['wine.csv']),delimiter=",",skiprows=1,dtype=np.float32)

    self.x=torch.from_numpy(xy[:,1:])#get all rows and start from 1st column, skip 0 row.
    self.y=torch.from_numpy(xy[:,[0]])#get all rows and only 0th column
    self.n_samples=xy.shape[0]

  def __getitem__(self,index):
       return self.x[index], self.y[index]    

  def __len__(self):  
      return self.n_samples

##dataset
data_set=WineDataset() # data_set object is used get index for every 178 observations of loaded file , done through __getitem__
                       # data_set is used to get length of file loaded , done through __len__ 

print(data_set.__dict__.keys()) #dict_keys(['x', 'y', 'n_samples'])
first_data=data_set[0] #__getitem__ is called and [0] index is pointed
features, target= first_data

print("total_no_of samples",data_set.n_samples)
print("length of dataset",len(data_set))




Saving wine.csv to wine (7).csv
dict_keys(['x', 'y', 'n_samples'])
total_no_of samples 178
length of dataset 178


In [51]:
#DataLoader
dataset2=WineDataset()


Saving wine.csv to wine (6).csv


In [52]:
print("total number of samples are ",dataset2.n_samples) #178
dataloader=DataLoader(dataset=dataset2,batch_size=4,shuffle=True,num_workers=2)
#batch size of 4 is created

#to get 1st batch

dataiter=iter(dataloader)
data=dataiter.next()

features,target=data

print(len(features))#4
print(type(features))#<class 'torch.Tensor'>


total number of samples are  178
4
<class 'torch.Tensor'>


In [56]:
#to go through entire dataset
dataloader1=DataLoader(dataset=dataset2,batch_size=20,shuffle=True,num_workers=2)
dataiter2=iter(dataloader1) #The iter() function creates an object which can be iterated one element at a time.


epochs=1
total_samples=len(dataset2)
batch_size=20
n_iterations= math.ceil(total_samples/batch_size)

print("no of iterations ",n_iterations,"\n")
print(dataset2.__dict__.keys())#dict_keys(['x', 'y', 'n_samples'])
print("\n")

for ind ,data in enumerate(range(n_iterations)):
        print("batch no ",ind)
        features,target=dataiter2.next()
        print("shape(features)",features.shape)#shape(features) torch.Size([20, 13])
       
        


no of iterations  9 

dict_keys(['x', 'y', 'n_samples'])


batch no  0
shape(features) torch.Size([20, 13])
batch no  1
shape(features) torch.Size([20, 13])
batch no  2
shape(features) torch.Size([20, 13])
batch no  3
shape(features) torch.Size([20, 13])
batch no  4
shape(features) torch.Size([20, 13])
batch no  5
shape(features) torch.Size([20, 13])
batch no  6
shape(features) torch.Size([20, 13])
batch no  7
shape(features) torch.Size([20, 13])
batch no  8
shape(features) torch.Size([18, 13])
